// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbwaP7Lml3gvY8KJ8rU5os8tQp3SJtIZ8',
    appId: '1:247168830374:web:d627f716b75356aff8dd67',
    messagingSenderId: '247168830374',
    projectId: 'loschucosapp',
    authDomain: 'loschucosapp.firebaseapp.com',
    storageBucket: 'loschucosapp.firebasestorage.app',
    measurementId: 'G-7C6B4CRZQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfcFXFAXzqRDpcZ8iBoXHlgROXTtvXcCQ',
    appId: '1:247168830374:android:af0a59cfb1f9ab25f8dd67',
    messagingSenderId: '247168830374',
    projectId: 'loschucosapp',
    storageBucket: 'loschucosapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI2GxtZ6o1M9VRrDNxkPBKt_Lkn1POrLo',
    appId: '1:247168830374:ios:64c4ee4dfb10d9caf8dd67',
    messagingSenderId: '247168830374',
    projectId: 'loschucosapp',
    storageBucket: 'loschucosapp.firebasestorage.app',
    iosClientId: '247168830374-l2fnfn5boe3vinjb6mhp9ifeq3jol8qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.losCuchosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI2GxtZ6o1M9VRrDNxkPBKt_Lkn1POrLo',
    appId: '1:247168830374:ios:d1fa6cbaeccd2676f8dd67',
    messagingSenderId: '247168830374',
    projectId: 'loschucosapp',
    storageBucket: 'loschucosapp.firebasestorage.app',
    iosClientId: '247168830374-na7fmreq0a0062sjojkh008b0vvbcavl.apps.googleusercontent.com',
    iosBundleId: 'com.example.losChucosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbwaP7Lml3gvY8KJ8rU5os8tQp3SJtIZ8',
    appId: '1:247168830374:web:0e683c78aab3d4c2f8dd67',
    messagingSenderId: '247168830374',
    projectId: 'loschucosapp',
    authDomain: 'loschucosapp.firebaseapp.com',
    storageBucket: 'loschucosapp.firebasestorage.app',
    measurementId: 'G-XW4FJ47JDL',
  );
}
